-- MySQL Script generated by MySQL Workbench
-- Fri Dec  4 22:59:09 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Universidade
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Universidade
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Universidade` DEFAULT CHARACTER SET utf8 ;
USE `Universidade` ;

-- -----------------------------------------------------
-- Table `Universidade`.`Universidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidade`.`Universidade` (
  `Código` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(50) NOT NULL,
  `Website` VARCHAR(100) NULL,
  `Email` VARCHAR(50) NOT NULL,
  `Telefone` VARCHAR(13) NOT NULL,
  `Facebook` VARCHAR(45) NULL,
  `Instagram` VARCHAR(45) NULL,
  `Reitor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Código`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Universidade`.`Funcionário`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidade`.`Funcionário` (
  `Número` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Função` VARCHAR(100) NOT NULL,
  `Telemóvel` VARCHAR(45) NOT NULL,
  `Rua` VARCHAR(45) NOT NULL,
  `Código Postal` VARCHAR(45) NOT NULL,
  `Localidade` VARCHAR(45) NOT NULL,
  `Universidade_Código` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Número`, `Universidade_Código`),
  INDEX `fk_Funcionário_Universidade1_idx` (`Universidade_Código` ASC) VISIBLE,
  CONSTRAINT `fk_Funcionário_Universidade1`
    FOREIGN KEY (`Universidade_Código`)
    REFERENCES `Universidade`.`Universidade` (`Código`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Universidade`.`Escola`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidade`.`Escola` (
  `Código` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `ID Diretor` VARCHAR(45) NOT NULL,
  `Universidade_Código` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Código`, `Universidade_Código`),
  INDEX `fk_Escola_Universidade1_idx` (`Universidade_Código` ASC) VISIBLE,
  CONSTRAINT `fk_Escola_Universidade1`
    FOREIGN KEY (`Universidade_Código`)
    REFERENCES `Universidade`.`Universidade` (`Código`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Universidade`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidade`.`Departamento` (
  `Código` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Escola_Código` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Código`, `Escola_Código`),
  INDEX `fk_Departamento_Escola1_idx` (`Escola_Código` ASC) VISIBLE,
  CONSTRAINT `fk_Departamento_Escola1`
    FOREIGN KEY (`Escola_Código`)
    REFERENCES `Universidade`.`Escola` (`Código`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Universidade`.`Docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidade`.`Docente` (
  `Número` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Telemóvel` VARCHAR(13) NULL,
  `Contrato` VARCHAR(45) NOT NULL,
  `Código Postal` VARCHAR(45) NOT NULL,
  `Rua` VARCHAR(45) NOT NULL,
  `Localidade` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NULL,
  `Departamento_Código` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Número`, `Departamento_Código`),
  INDEX `fk_Docente_Departamento1_idx` (`Departamento_Código` ASC) VISIBLE,
  CONSTRAINT `fk_Docente_Departamento1`
    FOREIGN KEY (`Departamento_Código`)
    REFERENCES `Universidade`.`Departamento` (`Código`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Universidade`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidade`.`Curso` (
  `Codigo` VARCHAR(45) NOT NULL,
  `Regime` VARCHAR(45) NOT NULL,
  `ID Diretor` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Escola_Código` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Codigo`, `Escola_Código`),
  INDEX `fk_Curso_Escola1_idx` (`Escola_Código` ASC) VISIBLE,
  CONSTRAINT `fk_Curso_Escola1`
    FOREIGN KEY (`Escola_Código`)
    REFERENCES `Universidade`.`Escola` (`Código`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Universidade`.`UC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidade`.`UC` (
  `Código` VARCHAR(45) NOT NULL,
  `ID Regente` VARCHAR(45) NOT NULL,
  `ECTS` INT NOT NULL,
  `Nome` VARCHAR(80) NOT NULL,
  `Ano` INT NOT NULL,
  `Semestre` INT NOT NULL,
  `Curso_Codigo` VARCHAR(45) NOT NULL,
  `Departamento_Código` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Código`, `Curso_Codigo`, `Departamento_Código`),
  INDEX `fk_UC_Curso1_idx` (`Curso_Codigo` ASC) VISIBLE,
  INDEX `fk_UC_Departamento1_idx` (`Departamento_Código` ASC) VISIBLE,
  CONSTRAINT `fk_UC_Curso1`
    FOREIGN KEY (`Curso_Codigo`)
    REFERENCES `Universidade`.`Curso` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UC_Departamento1`
    FOREIGN KEY (`Departamento_Código`)
    REFERENCES `Universidade`.`Departamento` (`Código`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Universidade`.`Docente_leciona_uc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidade`.`Docente_leciona_uc` (
  `Docente_Número` VARCHAR(45) NOT NULL,
  `UC_Código` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Docente_Número`, `UC_Código`),
  INDEX `fk_Docente_has_UC_UC1_idx` (`UC_Código` ASC) VISIBLE,
  INDEX `fk_Docente_has_UC_Docente1_idx` (`Docente_Número` ASC) VISIBLE,
  CONSTRAINT `fk_Docente_has_UC_Docente1`
    FOREIGN KEY (`Docente_Número`)
    REFERENCES `Universidade`.`Docente` (`Número`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Docente_has_UC_UC1`
    FOREIGN KEY (`UC_Código`)
    REFERENCES `Universidade`.`UC` (`Código`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Universidade`.`Turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidade`.`Turno` (
  `Número` INT NOT NULL,
  `Sala` VARCHAR(45) NULL,
  `Edifício` VARCHAR(45) NULL,
  `Hora Entrada` TIME NOT NULL,
  `Hora_Saída` TIME NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Docente_Número` VARCHAR(45) NOT NULL,
  `UC_Código` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Número`, `Docente_Número`, `UC_Código`),
  INDEX `fk_Turno_Docente_has_UC1_idx` (`Docente_Número` ASC, `UC_Código` ASC) VISIBLE,
  CONSTRAINT `fk_Turno_Docente_has_UC1`
    FOREIGN KEY (`Docente_Número` , `UC_Código`)
    REFERENCES `Universidade`.`Docente_leciona_uc` (`Docente_Número` , `UC_Código`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Universidade`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidade`.`Aluno` (
  `Número` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Telemovel` VARCHAR(13) NULL,
  `Codigo_Postal` VARCHAR(45) NOT NULL,
  `Rua` VARCHAR(45) NOT NULL,
  `Ano_Inscricao` VARCHAR(45) NOT NULL,
  `Estatuto` VARCHAR(45) NOT NULL,
  `Localidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Número`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Universidade`.`Aluno_frequenta_UC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidade`.`Aluno_frequenta_UC` (
  `Aluno_Número` VARCHAR(45) NOT NULL,
  `UC_Código` VARCHAR(45) NOT NULL,
  `Turno_Número` INT NOT NULL,
  `Ano Letivo` VARCHAR(45) NOT NULL,
  `Admitido` TINYINT NULL,
  `Classificação` FLOAT NULL,
  `Época` VARCHAR(45) NULL,
  PRIMARY KEY (`Aluno_Número`, `UC_Código`, `Turno_Número`),
  INDEX `fk_Aluno_has_UC_UC1_idx` (`UC_Código` ASC) VISIBLE,
  INDEX `fk_Aluno_has_UC_Aluno1_idx` (`Aluno_Número` ASC) VISIBLE,
  INDEX `fk_Aluno_está_registado_Turno1_idx` (`Turno_Número` ASC) VISIBLE,
  CONSTRAINT `fk_Aluno_has_UC_Aluno1`
    FOREIGN KEY (`Aluno_Número`)
    REFERENCES `Universidade`.`Aluno` (`Número`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_has_UC_UC1`
    FOREIGN KEY (`UC_Código`)
    REFERENCES `Universidade`.`UC` (`Código`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_está_registado_Turno1`
    FOREIGN KEY (`Turno_Número`)
    REFERENCES `Universidade`.`Turno` (`Número`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Universidade`.`Matrícula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidade`.`Matrícula` (
  `ID` VARCHAR(45) NOT NULL,
  `Ano_Letivo` VARCHAR(45) NULL,
  `Aluno_Número` VARCHAR(45) NOT NULL,
  `Curso_Codigo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`, `Aluno_Número`, `Curso_Codigo`),
  INDEX `fk_Matrícula_Aluno1_idx` (`Aluno_Número` ASC) VISIBLE,
  INDEX `fk_Matrícula_Curso1_idx` (`Curso_Codigo` ASC) VISIBLE,
  CONSTRAINT `fk_Matrícula_Aluno1`
    FOREIGN KEY (`Aluno_Número`)
    REFERENCES `Universidade`.`Aluno` (`Número`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matrícula_Curso1`
    FOREIGN KEY (`Curso_Codigo`)
    REFERENCES `Universidade`.`Curso` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
